### ISSUE TITLE
Add English translation for the documentation

### ISSUE THREAD

**Issue by nicolasmaia** [jiacai2050/gooreplacer#34]
I suspect this is a great project, but I can't be certain because of the language barrier...

**Comment by jiacai2050** [comment]
Thanks for your attention.

This extension is mainly used for redirecting  Fonts/JS/CSS hosted on Google. Because Google is blocked  from my country, those resources are unaccessible too.

Later on, I have added features  allowing user-defined rules. 

All in all, if you aren't in China, I don't think this extension is useful for you.

**Comment by nicolasmaia** [comment]
You'd be surprised. Projects like https://github.com/Eloston/ungoogled-chromium could perhaps use your work.

**Comment by jiacai2050** [comment]
Wow, I have never expected that you people want to ungoogle.

I will dig into that project. Thank you.

**Comment by jiacai2050** [comment]
Sorry for my delay. I have added a English-version README
- https://github.com/jiacai2050/gooreplacer4chrome/blob/master/README-en.md

If you are still interested at this, let me know if there is anything vague

**Comment by jiacai2050** [comment]
Close now, feel free to open again. 😊
